In [10]:
import pandas as pd

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [16]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [17]:
pd.__version__

'3.0.6'

In [18]:
len(df)


10000

In [19]:
df['fuel_type'].nunique()

3

In [21]:
print(df.isnull().any().sum())

2


In [23]:
print(df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max())

41.2


In [25]:
print(df['horsepower'].median())

254.0


In [26]:
hpFreq = df['horsepower'].value_counts().index[0]

In [27]:
hpFreq

np.float64(252.0)

In [28]:
print(df['horsepower'].fillna(hpFreq).median())

252.0


In [29]:
import numpy as np

In [30]:
X = df[df['origin'] == 'Asia'][['model_year', 'vehicle_weight']].head(7).to_numpy()

In [31]:
X

array([[1996, 4240],
       [1992, 4310],
       [1997, 4230],
       [1978, 4420],
       [2007, 3950],
       [2021, 4750],
       [2019, 4450]])

In [32]:
XTX = X.T @ X

In [33]:
XTX

array([[ 28041424,  60750580],
       [ 60750580, 131950500]])

In [34]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [35]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [36]:
w = np.linalg.inv(XTX) @ X.T @ y

In [37]:
w

array([0.2327492 , 0.13644777])

In [38]:
print(w.sum())

0.3691969690492686
